// UserProfilePage
// This file was auto-generated by Mason
import 'package:flutter/material.dart';
import '../widgets/user_profile_widget.dart';

class UserProfilePage extends StatelessWidget {
  const UserProfilePage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('UserProfile'),
      ),
      body: UserProfileWidget(),
    );
  }
}
