// UserProfileRepositoryImpl
// This file was auto-generated by Mason
import '../../domain/entities/user_profile_entity.dart';
import '../../domain/repositories/user_profile_repository.dart';
import '../datasources/user_profile_data_source.dart';
import '../models/user_profile_model.dart';

class UserProfileRepositoryImpl implements UserProfileRepository {
  final UserProfileDataSource dataSource;
  
  UserProfileRepositoryImpl({
    required this.dataSource,
  });
  
  @override
  Future<List<UserProfileEntity>> getAll() async {
    final result = await dataSource.getAll();
    return result.map((model) => model).toList();
  }
  
  @override
  Future<UserProfileEntity> getById(String id) async {
    return await dataSource.getById(id);
  }
  
  @override
  Future<void> create(UserProfileEntity entity) async {
    await dataSource.create(UserProfileModel.fromEntity(entity));
  }
  
  @override
  Future<void> update(UserProfileEntity entity) async {
    await dataSource.update(UserProfileModel.fromEntity(entity));
  }
  
  @override
  Future<void> delete(String id) async {
    await dataSource.delete(id);
  }
}
