include: package:lints/recommended.yaml

linter:
  rules:
    - public_member_api_docs 
    - prefer_relative_imports
    - prefer_single_quotes
    - sort_child_properties_last
    - sort_constructors_first
    - always_declare_return_types
    - avoid_empty_else
    - avoid_redundant_argument_values
    - directives_ordering
    - avoid_print
    - parameter_assignments
    - prefer_const_constructors
    - prefer_final_fields
    - require_trailing_commas

analyzer:
  errors:
    todo: ignore
    public_member_api_docs: ignore
    file_names: ignore
  exclude:
    - "build/**"
    - "**/*.g.dart"
    - "**/*.gr.dart"
