name: flutter_bunny
description: A CLI tool for creating and managing Flutter applications with best practices
version: 1.0.6-beta.7
repository: https://github.com/demola234/bunny_cli
homepage: https://bunny.demola.dev/flutterbunnycli
issue_tracker: https://github.com/demola234/bunny_cli/issues
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  ansicolor: ^2.0.2
  args: ^2.5.0
  cli_completion: ^0.5.0
  cli_pkg: ^2.12.0
  collection: ^1.18.0
  crypto: ^3.0.6
  glob: ^2.1.2
  grinder: ^0.9.5
  jsonc: ^0.0.3
  logging: ^1.0.0
  mason: ^0.1.0-dev.53
  mason_logger: ^0.3.3
  meta: ^1.14.0
  package_config: ^2.1.0
  path: ^1.9.0
  pub_updater: ^0.5.0
  sprintf: ^7.0.0
  universal_io: ^2.2.2
  win32: ^5.6.0

dev_dependencies:
  build_runner: ^2.4.9
  build_verify: ^3.1.0
  build_version: ^2.1.1
  lints: ^5.1.1
  mocktail: ^1.0.3
  test: ^1.24.0

# Enable platform detection to demonstrate platform support
platforms:
  ? linux
  ? macos
  ? windows

# Add additional information for pub.dev package page
topics:
  - cli
  - flutter
  - code-generation
  - templates

executables:
  ? flutter_bunny
