// UserProfileEntity
// This file was auto-generated by Mason

class UserProfileEntity {
  final String id;
  final String name;
  // Add more fields as needed
  
  UserProfileEntity({
    required this.id,
    required this.name,
  });
}
