// AuthenticationUseCase
// This file was auto-generated by Mason
import '../entities/authentication_entity.dart';
import '../repositories/authentication_repository.dart';

class GetAuthenticationUseCase {
  final AuthenticationRepository repository;
  
  GetAuthenticationUseCase(this.repository);
  
  Future<List<AuthenticationEntity>> execute() {
    return repository.getAll();
  }
}

class GetAuthenticationByIdUseCase {
  final AuthenticationRepository repository;
  
  GetAuthenticationByIdUseCase(this.repository);
  
  Future<AuthenticationEntity> execute(String id) {
    return repository.getById(id);
  }
}
