name: Bug Report
description: Report a bug in Flutter Bunny
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        
  - type: checkboxes
    id: type
    attributes:
      label: Type
      description: Please select the issue type (bugs should be selected)
      options:
        - label: Bug
          required: true
        - label: Feature Request
          required: false
        - label: Documentation
          required: false
        - label: Maintenance
          required: false
        - label: Question
          required: false
          
  - type: input
    id: version
    attributes:
      label: Flutter Bunny Version
      description: What version of Flutter Bunny are you using?
      placeholder: e.g., 1.1.0
    validations:
      required: true
      
  - type: input
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      placeholder: e.g., macOS 12.6, Windows 11, Ubuntu 22.04
    validations:
      required: true
      
  - type: input
    id: dart
    attributes:
      label: Dart Version
      description: What version of Dart are you using?
      placeholder: e.g., 2.18.2
    validations:
      required: false
      
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the bug
      placeholder: Tell us what happened
    validations:
      required: true
      
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run command '...'
        2. Enter '...'
        3. See error
    validations:
      required: true
      
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen
    validations:
      required: true
      
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened (include error messages, logs, screenshots if applicable)
      placeholder: |
        Paste any relevant error messages, logs, or output here.
        
        ```
        Error output goes here
        ```
    validations:
      required: true
      
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Any additional information, configuration, or data that might help solve the issue.
    validations:
      required: false
      
  - type: checkboxes
    id: checks
    attributes:
      label: Pre-submission Checks
      options:
        - label: I have searched for similar issues before creating this one
          required: true
        - label: I have tested with the latest version of Flutter Bunny
          required: true