blank_issues_enabled: false
contact_links:
  - name: Flutter Bunny Discussions
    url: https://github.com/demola234/flutter_bunny_cli/discussions
    about: Ask questions and discuss with other community members
  - name: Documentation
    url: https://github.com/demola234/flutter_bunny_cli/blob/main/README.md
    about: Check the documentation first to see if your question is already answered