// AuthenticationEntity
// This file was auto-generated by Mason

class AuthenticationEntity {
  final String id;
  final String name;
  // Add more fields as needed
  
  AuthenticationEntity({
    required this.id,
    required this.name,
  });
}
