// UserProfileWidget
// This file was auto-generated by Mason
import 'package:flutter/material.dart';

class UserProfileWidget extends StatelessWidget {
  const UserProfileWidget({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Center(
      child: Text('UserProfile Feature'),
    );
  }
}
