// AuthenticationWidget
// This file was auto-generated by Mason
import 'package:flutter/material.dart';

class AuthenticationWidget extends StatelessWidget {
  const AuthenticationWidget({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Center(
      child: Text('Authentication Feature'),
    );
  }
}
