// AuthenticationRepositoryImpl
// This file was auto-generated by Mason
import '../../domain/entities/authentication_entity.dart';
import '../../domain/repositories/authentication_repository.dart';
import '../datasources/authentication_data_source.dart';
import '../models/authentication_model.dart';

class AuthenticationRepositoryImpl implements AuthenticationRepository {
  final AuthenticationDataSource dataSource;
  
  AuthenticationRepositoryImpl({
    required this.dataSource,
  });
  
  @override
  Future<List<AuthenticationEntity>> getAll() async {
    final result = await dataSource.getAll();
    return result.map((model) => model).toList();
  }
  
  @override
  Future<AuthenticationEntity> getById(String id) async {
    return await dataSource.getById(id);
  }
  
  @override
  Future<void> create(AuthenticationEntity entity) async {
    await dataSource.create(AuthenticationModel.fromEntity(entity));
  }
  
  @override
  Future<void> update(AuthenticationEntity entity) async {
    await dataSource.update(AuthenticationModel.fromEntity(entity));
  }
  
  @override
  Future<void> delete(String id) async {
    await dataSource.delete(id);
  }
}
