// AuthenticationModel
// This file was auto-generated by Mason
import '../../domain/entities/authentication_entity.dart';

class AuthenticationModel extends AuthenticationEntity {
  AuthenticationModel({
    required String id,
    required String name,
  }) : super(
    id: id,
    name: name,
  );
  
  factory AuthenticationModel.fromJson(Map<String, dynamic> json) {
    return AuthenticationModel(
      id: json['id'],
      name: json['name'],
    );
  }
  
  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'name': name,
    };
  }
  
  factory AuthenticationModel.fromEntity(AuthenticationEntity entity) {
    return AuthenticationModel(
      id: entity.id,
      name: entity.name,
    );
  }
}
