// UserProfileDataSource
// This file was auto-generated by Mason
import '../models/user_profile_model.dart';

abstract class UserProfileDataSource {
  Future<List<UserProfileModel>> getAll();
  Future<UserProfileModel> getById(String id);
  Future<void> create(UserProfileModel model);
  Future<void> update(UserProfileModel model);
  Future<void> delete(String id);
}

class UserProfileRemoteDataSource implements UserProfileDataSource {
  // TODO: Implement remote data source (API calls, etc.)
  
  @override
  Future<List<UserProfileModel>> getAll() async {
    // TODO: Implement API call
    return [];
  }
  
  @override
  Future<UserProfileModel> getById(String id) async {
    // TODO: Implement API call
    throw UnimplementedError();
  }
  
  @override
  Future<void> create(UserProfileModel model) async {
    // TODO: Implement API call
  }
  
  @override
  Future<void> update(UserProfileModel model) async {
    // TODO: Implement API call
  }
  
  @override
  Future<void> delete(String id) async {
    // TODO: Implement API call
  }
}

class UserProfileLocalDataSource implements UserProfileDataSource {
  // TODO: Implement local data source (shared prefs, database, etc.)
  
  @override
  Future<List<UserProfileModel>> getAll() async {
    // TODO: Implement local storage retrieval
    return [];
  }
  
  @override
  Future<UserProfileModel> getById(String id) async {
    // TODO: Implement local storage retrieval
    throw UnimplementedError();
  }
  
  @override
  Future<void> create(UserProfileModel model) async {
    // TODO: Implement local storage saving
  }
  
  @override
  Future<void> update(UserProfileModel model) async {
    // TODO: Implement local storage updating
  }
  
  @override
  Future<void> delete(String id) async {
    // TODO: Implement local storage deletion
  }
}
