// AuthenticationRepository interface
// This file was auto-generated by Mason
import '../entities/authentication_entity.dart';

abstract class AuthenticationRepository {
  Future<List<AuthenticationEntity>> getAll();
  Future<AuthenticationEntity> getById(String id);
  Future<void> create(AuthenticationEntity entity);
  Future<void> update(AuthenticationEntity entity);
  Future<void> delete(String id);
}
