// AuthenticationDataSource
// This file was auto-generated by Mason
import '../models/authentication_model.dart';

abstract class AuthenticationDataSource {
  Future<List<AuthenticationModel>> getAll();
  Future<AuthenticationModel> getById(String id);
  Future<void> create(AuthenticationModel model);
  Future<void> update(AuthenticationModel model);
  Future<void> delete(String id);
}

class AuthenticationRemoteDataSource implements AuthenticationDataSource {
  // TODO: Implement remote data source (API calls, etc.)
  
  @override
  Future<List<AuthenticationModel>> getAll() async {
    // TODO: Implement API call
    return [];
  }
  
  @override
  Future<AuthenticationModel> getById(String id) async {
    // TODO: Implement API call
    throw UnimplementedError();
  }
  
  @override
  Future<void> create(AuthenticationModel model) async {
    // TODO: Implement API call
  }
  
  @override
  Future<void> update(AuthenticationModel model) async {
    // TODO: Implement API call
  }
  
  @override
  Future<void> delete(String id) async {
    // TODO: Implement API call
  }
}

class AuthenticationLocalDataSource implements AuthenticationDataSource {
  // TODO: Implement local data source (shared prefs, database, etc.)
  
  @override
  Future<List<AuthenticationModel>> getAll() async {
    // TODO: Implement local storage retrieval
    return [];
  }
  
  @override
  Future<AuthenticationModel> getById(String id) async {
    // TODO: Implement local storage retrieval
    throw UnimplementedError();
  }
  
  @override
  Future<void> create(AuthenticationModel model) async {
    // TODO: Implement local storage saving
  }
  
  @override
  Future<void> update(AuthenticationModel model) async {
    // TODO: Implement local storage updating
  }
  
  @override
  Future<void> delete(String id) async {
    // TODO: Implement local storage deletion
  }
}
