// Dependency injection setup
// Generated by Mason

// This file will be used to setup dependency injection
// with a package like get_it, injectable, etc.

void setupInjector() {
  // TODO: Register dependencies
}
