// UserProfileRepository interface
// This file was auto-generated by Mason
import '../entities/user_profile_entity.dart';

abstract class UserProfileRepository {
  Future<List<UserProfileEntity>> getAll();
  Future<UserProfileEntity> getById(String id);
  Future<void> create(UserProfileEntity entity);
  Future<void> update(UserProfileEntity entity);
  Future<void> delete(String id);
}
