name: Auto Tag Release

on:
  push:
    branches:
      - main
    paths:
      - "pubspec.yaml" # Trigger when pubspec is updated (likely version changes)

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Dart
        uses: dart-lang/setup-dart@v1

      - name: Extract version from pubspec
        id: version
        run: |
          VERSION=$(grep '^version:' pubspec.yaml | sed 's/version: //' | tr -d ' ' | tr -d '\r')
          echo "VERSION=v$VERSION" >> $GITHUB_ENV
          echo "Version extracted: v$VERSION"

      - name: Check if tag exists
        id: check_tag
        run: |
          if git tag -l "${{ env.VERSION }}" | grep -q "${{ env.VERSION }}"; then
            echo "TAG_EXISTS=true" >> $GITHUB_ENV
            echo "Tag ${{ env.VERSION }} already exists"
          else
            echo "TAG_EXISTS=false" >> $GITHUB_ENV
            echo "Tag ${{ env.VERSION }} does not exist"
          fi

      - name: Create and push tag
        if: env.TAG_EXISTS == 'false'
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git tag -a ${{ env.VERSION }} -m "Release ${{ env.VERSION }}"
          git push origin ${{ env.VERSION }}
          echo "Created and pushed tag: ${{ env.VERSION }}"
