name: Release Homebrew Formula

on:
  release:
    types: [published]

jobs:
  homebrew:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up Dart
        uses: dart-lang/setup-dart@v1
        
      - name: Install dependencies
        run: dart pub get

      - name: List available tasks
        run: dart run grinder -h
        
      - name: Generate Homebrew formula
        run: dart run grinder homebrew-formula --version=${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout homebrew-tap repo
        uses: actions/checkout@v3
        with:
          repository: demola234/homebrew-tap
          path: homebrew-tap
          token: ${{ secrets.GH_PAT }}
        
      - name: Copy formula to homebrew-tap
        run: cp flutter_bunny.rb homebrew-tap/

      - name: Create PR in homebrew-tap
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GH_PAT }}
          path: homebrew-tap
          commit-message: "Update formula to ${{ github.ref_name }}"
          title: "Update formula to ${{ github.ref_name }}"
          body: |
            This PR updates the Homebrew formula to version ${{ github.ref_name }}.
            Created automatically by GitHub Actions.
          branch: update-formula-${{ github.ref_name }}
          base: main

      - name: Debug info
        run: |
          echo "Generated formula content:"
          cat flutter_bunny.rb